version : '3'
services:
  own-image:
    image: 723466690293.dkr.ecr.us-east-1.amazonaws.com/my-app:latest
    ports:
      - 3000:3000
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
  mongo-express:
      image: mongo-express:latest
      ports:
        - 8081:8081
      restart: always
      environment:
        - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
        - ME_CONFIG_MONGODB_ADMINPASSWORD=password
        - ME_CONFIG_MONGODB_SERVER=mongodb
